-- Shared options
vim.o.termguicolors   = true
vim.o.number          = true
vim.o.relativenumber  = true
vim.o.expandtab       = true
vim.o.shiftwidth      = 2
vim.o.tabstop         = 2
vim.o.smartindent     = true
vim.o.ignorecase      = true
vim.o.smartcase       = true